// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtbpaKduNXTEfQ0zvSBs_G_g7zzbXyw0A',
    appId: '1:7987844130:web:5cc612bf1f7b8d5147e67b',
    messagingSenderId: '7987844130',
    projectId: 'mynotes-project-firebase',
    authDomain: 'mynotes-project-firebase.firebaseapp.com',
    storageBucket: 'mynotes-project-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1eQHxKeL6-6JhwI8uthxnNA1GM4xS4Ds',
    appId: '1:7987844130:android:5df489959d031f9047e67b',
    messagingSenderId: '7987844130',
    projectId: 'mynotes-project-firebase',
    storageBucket: 'mynotes-project-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvI5qAh2bJZ0sc6QhSZM00nWV1S3TkKCg',
    appId: '1:7987844130:ios:8350d80497142d7b47e67b',
    messagingSenderId: '7987844130',
    projectId: 'mynotes-project-firebase',
    storageBucket: 'mynotes-project-firebase.appspot.com',
    iosClientId: '7987844130-oogmsb63u9emms1hfkhk3d8o5io9fad7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
